// Copyright (c) Kyle Huggins
// SPDX-License-Identifier: BSD-3-Clause

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: nexus/v2/api.proto

// Package nexus provides APIs for managing encrypted secrets and their metadata.

package nexusv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_nexus_v2_api_proto protoreflect.FileDescriptor

const file_nexus_v2_api_proto_rawDesc = "" +
	"\n" +
	"\x12nexus/v2/api.proto\x12\bnexus.v2B\x88\x01\n" +
	"\fcom.nexus.v2B\bApiProtoP\x01Z-github.com/hugginsio/kv2/api/nexus/v2;nexusv2\xa2\x02\x03NXX\xaa\x02\bNexus.V2\xca\x02\bNexus\\V2\xe2\x02\x14Nexus\\V2\\GPBMetadata\xea\x02\tNexus::V2b\x06proto3"

var file_nexus_v2_api_proto_goTypes = []any{}
var file_nexus_v2_api_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_nexus_v2_api_proto_init() }
func file_nexus_v2_api_proto_init() {
	if File_nexus_v2_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nexus_v2_api_proto_rawDesc), len(file_nexus_v2_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nexus_v2_api_proto_goTypes,
		DependencyIndexes: file_nexus_v2_api_proto_depIdxs,
	}.Build()
	File_nexus_v2_api_proto = out.File
	file_nexus_v2_api_proto_goTypes = nil
	file_nexus_v2_api_proto_depIdxs = nil
}
