// Copyright (c) Kyle Huggins
// SPDX-License-Identifier: BSD-3-Clause

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: nexus/v2/api.proto

// Package nexus provides APIs for managing encrypted secrets and their
// metadata. Nexus stores provided values as-is, and the client should
// encrypt the content prior to making the request.

package nexusv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	PublicKey     string                 `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSecretRequest) Reset() {
	*x = CreateSecretRequest{}
	mi := &file_nexus_v2_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSecretRequest) ProtoMessage() {}

func (x *CreateSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_v2_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSecretRequest.ProtoReflect.Descriptor instead.
func (*CreateSecretRequest) Descriptor() ([]byte, []int) {
	return file_nexus_v2_api_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSecretRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateSecretRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *CreateSecretRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

type CreateSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSecretResponse) Reset() {
	*x = CreateSecretResponse{}
	mi := &file_nexus_v2_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSecretResponse) ProtoMessage() {}

func (x *CreateSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_v2_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSecretResponse.ProtoReflect.Descriptor instead.
func (*CreateSecretResponse) Descriptor() ([]byte, []int) {
	return file_nexus_v2_api_proto_rawDescGZIP(), []int{1}
}

type ListSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSecretRequest) Reset() {
	*x = ListSecretRequest{}
	mi := &file_nexus_v2_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSecretRequest) ProtoMessage() {}

func (x *ListSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_v2_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSecretRequest.ProtoReflect.Descriptor instead.
func (*ListSecretRequest) Descriptor() ([]byte, []int) {
	return file_nexus_v2_api_proto_rawDescGZIP(), []int{2}
}

type ListSecretInner struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Versions      []uint32               `protobuf:"varint,2,rep,packed,name=versions,proto3" json:"versions,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,3,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSecretInner) Reset() {
	*x = ListSecretInner{}
	mi := &file_nexus_v2_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSecretInner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSecretInner) ProtoMessage() {}

func (x *ListSecretInner) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_v2_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSecretInner.ProtoReflect.Descriptor instead.
func (*ListSecretInner) Descriptor() ([]byte, []int) {
	return file_nexus_v2_api_proto_rawDescGZIP(), []int{3}
}

func (x *ListSecretInner) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ListSecretInner) GetVersions() []uint32 {
	if x != nil {
		return x.Versions
	}
	return nil
}

func (x *ListSecretInner) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *ListSecretInner) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ListSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secrets       []*ListSecretInner     `protobuf:"bytes,1,rep,name=secrets,proto3" json:"secrets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSecretResponse) Reset() {
	*x = ListSecretResponse{}
	mi := &file_nexus_v2_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSecretResponse) ProtoMessage() {}

func (x *ListSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_v2_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSecretResponse.ProtoReflect.Descriptor instead.
func (*ListSecretResponse) Descriptor() ([]byte, []int) {
	return file_nexus_v2_api_proto_rawDescGZIP(), []int{4}
}

func (x *ListSecretResponse) GetSecrets() []*ListSecretInner {
	if x != nil {
		return x.Secrets
	}
	return nil
}

type GetSecretByTitleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretByTitleRequest) Reset() {
	*x = GetSecretByTitleRequest{}
	mi := &file_nexus_v2_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretByTitleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretByTitleRequest) ProtoMessage() {}

func (x *GetSecretByTitleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_v2_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretByTitleRequest.ProtoReflect.Descriptor instead.
func (*GetSecretByTitleRequest) Descriptor() ([]byte, []int) {
	return file_nexus_v2_api_proto_rawDescGZIP(), []int{5}
}

func (x *GetSecretByTitleRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type GetSecretByTitleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Versions      []uint32               `protobuf:"varint,1,rep,packed,name=versions,proto3" json:"versions,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,2,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretByTitleResponse) Reset() {
	*x = GetSecretByTitleResponse{}
	mi := &file_nexus_v2_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretByTitleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretByTitleResponse) ProtoMessage() {}

func (x *GetSecretByTitleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_v2_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretByTitleResponse.ProtoReflect.Descriptor instead.
func (*GetSecretByTitleResponse) Descriptor() ([]byte, []int) {
	return file_nexus_v2_api_proto_rawDescGZIP(), []int{6}
}

func (x *GetSecretByTitleResponse) GetVersions() []uint32 {
	if x != nil {
		return x.Versions
	}
	return nil
}

func (x *GetSecretByTitleResponse) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *GetSecretByTitleResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetSecretVersionByTitleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Version       *uint32                `protobuf:"varint,2,opt,name=version,proto3,oneof" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretVersionByTitleRequest) Reset() {
	*x = GetSecretVersionByTitleRequest{}
	mi := &file_nexus_v2_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretVersionByTitleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretVersionByTitleRequest) ProtoMessage() {}

func (x *GetSecretVersionByTitleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_v2_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretVersionByTitleRequest.ProtoReflect.Descriptor instead.
func (*GetSecretVersionByTitleRequest) Descriptor() ([]byte, []int) {
	return file_nexus_v2_api_proto_rawDescGZIP(), []int{7}
}

func (x *GetSecretVersionByTitleRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetSecretVersionByTitleRequest) GetVersion() uint32 {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return 0
}

type GetSecretVersionByTitleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       *uint32                `protobuf:"varint,1,opt,name=version,proto3,oneof" json:"version,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,3,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretVersionByTitleResponse) Reset() {
	*x = GetSecretVersionByTitleResponse{}
	mi := &file_nexus_v2_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretVersionByTitleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretVersionByTitleResponse) ProtoMessage() {}

func (x *GetSecretVersionByTitleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_v2_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretVersionByTitleResponse.ProtoReflect.Descriptor instead.
func (*GetSecretVersionByTitleResponse) Descriptor() ([]byte, []int) {
	return file_nexus_v2_api_proto_rawDescGZIP(), []int{8}
}

func (x *GetSecretVersionByTitleResponse) GetVersion() uint32 {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return 0
}

func (x *GetSecretVersionByTitleResponse) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *GetSecretVersionByTitleResponse) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *GetSecretVersionByTitleResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type UpdateSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	PublicKey     string                 `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	User          string                 `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSecretRequest) Reset() {
	*x = UpdateSecretRequest{}
	mi := &file_nexus_v2_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSecretRequest) ProtoMessage() {}

func (x *UpdateSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_v2_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSecretRequest.ProtoReflect.Descriptor instead.
func (*UpdateSecretRequest) Descriptor() ([]byte, []int) {
	return file_nexus_v2_api_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateSecretRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateSecretRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *UpdateSecretRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *UpdateSecretRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

type UpdateSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSecretResponse) Reset() {
	*x = UpdateSecretResponse{}
	mi := &file_nexus_v2_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSecretResponse) ProtoMessage() {}

func (x *UpdateSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_v2_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSecretResponse.ProtoReflect.Descriptor instead.
func (*UpdateSecretResponse) Descriptor() ([]byte, []int) {
	return file_nexus_v2_api_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateSecretResponse) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

var File_nexus_v2_api_proto protoreflect.FileDescriptor

const file_nexus_v2_api_proto_rawDesc = "" +
	"\n" +
	"\x12nexus/v2/api.proto\x12\bnexus.v2\"d\n" +
	"\x13CreateSecretRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\tR\tpublicKey\"\x16\n" +
	"\x14CreateSecretResponse\"\x13\n" +
	"\x11ListSecretRequest\"\x81\x01\n" +
	"\x0fListSecretInner\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x1a\n" +
	"\bversions\x18\x02 \x03(\rR\bversions\x12\x1d\n" +
	"\n" +
	"created_by\x18\x03 \x01(\tR\tcreatedBy\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\"I\n" +
	"\x12ListSecretResponse\x123\n" +
	"\asecrets\x18\x01 \x03(\v2\x19.nexus.v2.ListSecretInnerR\asecrets\"/\n" +
	"\x17GetSecretByTitleRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\"t\n" +
	"\x18GetSecretByTitleResponse\x12\x1a\n" +
	"\bversions\x18\x01 \x03(\rR\bversions\x12\x1d\n" +
	"\n" +
	"created_by\x18\x02 \x01(\tR\tcreatedBy\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\tR\tcreatedAt\"a\n" +
	"\x1eGetSecretVersionByTitleRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x1d\n" +
	"\aversion\x18\x02 \x01(\rH\x00R\aversion\x88\x01\x01B\n" +
	"\n" +
	"\b_version\"\xa4\x01\n" +
	"\x1fGetSecretVersionByTitleResponse\x12\x1d\n" +
	"\aversion\x18\x01 \x01(\rH\x00R\aversion\x88\x01\x01\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\x12\x1d\n" +
	"\n" +
	"created_by\x18\x03 \x01(\tR\tcreatedBy\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAtB\n" +
	"\n" +
	"\b_version\"x\n" +
	"\x13UpdateSecretRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\tR\tpublicKey\x12\x12\n" +
	"\x04user\x18\x04 \x01(\tR\x04user\"0\n" +
	"\x14UpdateSecretResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion2\xf8\x01\n" +
	"\x0fKv2NexusService\x12G\n" +
	"\n" +
	"ListSecret\x12\x1b.nexus.v2.ListSecretRequest\x1a\x1c.nexus.v2.ListSecretResponse\x12M\n" +
	"\fCreateSecret\x12\x1d.nexus.v2.CreateSecretRequest\x1a\x1e.nexus.v2.CreateSecretResponse\x12M\n" +
	"\fUpdateSecret\x12\x1d.nexus.v2.UpdateSecretRequest\x1a\x1e.nexus.v2.UpdateSecretResponseB\x88\x01\n" +
	"\fcom.nexus.v2B\bApiProtoP\x01Z-github.com/hugginsio/kv2/api/nexus/v2;nexusv2\xa2\x02\x03NXX\xaa\x02\bNexus.V2\xca\x02\bNexus\\V2\xe2\x02\x14Nexus\\V2\\GPBMetadata\xea\x02\tNexus::V2b\x06proto3"

var (
	file_nexus_v2_api_proto_rawDescOnce sync.Once
	file_nexus_v2_api_proto_rawDescData []byte
)

func file_nexus_v2_api_proto_rawDescGZIP() []byte {
	file_nexus_v2_api_proto_rawDescOnce.Do(func() {
		file_nexus_v2_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nexus_v2_api_proto_rawDesc), len(file_nexus_v2_api_proto_rawDesc)))
	})
	return file_nexus_v2_api_proto_rawDescData
}

var file_nexus_v2_api_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_nexus_v2_api_proto_goTypes = []any{
	(*CreateSecretRequest)(nil),             // 0: nexus.v2.CreateSecretRequest
	(*CreateSecretResponse)(nil),            // 1: nexus.v2.CreateSecretResponse
	(*ListSecretRequest)(nil),               // 2: nexus.v2.ListSecretRequest
	(*ListSecretInner)(nil),                 // 3: nexus.v2.ListSecretInner
	(*ListSecretResponse)(nil),              // 4: nexus.v2.ListSecretResponse
	(*GetSecretByTitleRequest)(nil),         // 5: nexus.v2.GetSecretByTitleRequest
	(*GetSecretByTitleResponse)(nil),        // 6: nexus.v2.GetSecretByTitleResponse
	(*GetSecretVersionByTitleRequest)(nil),  // 7: nexus.v2.GetSecretVersionByTitleRequest
	(*GetSecretVersionByTitleResponse)(nil), // 8: nexus.v2.GetSecretVersionByTitleResponse
	(*UpdateSecretRequest)(nil),             // 9: nexus.v2.UpdateSecretRequest
	(*UpdateSecretResponse)(nil),            // 10: nexus.v2.UpdateSecretResponse
}
var file_nexus_v2_api_proto_depIdxs = []int32{
	3,  // 0: nexus.v2.ListSecretResponse.secrets:type_name -> nexus.v2.ListSecretInner
	2,  // 1: nexus.v2.Kv2NexusService.ListSecret:input_type -> nexus.v2.ListSecretRequest
	0,  // 2: nexus.v2.Kv2NexusService.CreateSecret:input_type -> nexus.v2.CreateSecretRequest
	9,  // 3: nexus.v2.Kv2NexusService.UpdateSecret:input_type -> nexus.v2.UpdateSecretRequest
	4,  // 4: nexus.v2.Kv2NexusService.ListSecret:output_type -> nexus.v2.ListSecretResponse
	1,  // 5: nexus.v2.Kv2NexusService.CreateSecret:output_type -> nexus.v2.CreateSecretResponse
	10, // 6: nexus.v2.Kv2NexusService.UpdateSecret:output_type -> nexus.v2.UpdateSecretResponse
	4,  // [4:7] is the sub-list for method output_type
	1,  // [1:4] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_nexus_v2_api_proto_init() }
func file_nexus_v2_api_proto_init() {
	if File_nexus_v2_api_proto != nil {
		return
	}
	file_nexus_v2_api_proto_msgTypes[7].OneofWrappers = []any{}
	file_nexus_v2_api_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nexus_v2_api_proto_rawDesc), len(file_nexus_v2_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nexus_v2_api_proto_goTypes,
		DependencyIndexes: file_nexus_v2_api_proto_depIdxs,
		MessageInfos:      file_nexus_v2_api_proto_msgTypes,
	}.Build()
	File_nexus_v2_api_proto = out.File
	file_nexus_v2_api_proto_goTypes = nil
	file_nexus_v2_api_proto_depIdxs = nil
}
