# https://taskfile.dev
# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: 3

tasks:
  default:
    cmds:
      - task -l
      - dagger functions
  test:
    desc: run all tests
    cmd: dagger call test --source=.
  server:dev:
    desc: run the server directly
    dir: "cmd/server"
    cmd: go run .
    dotenv:
      - .env
