# https://taskfile.dev
# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: 3

tasks:
  codegen:
    desc: Run code generation
    cmds:
      - "buf generate --clean"
  dev:nexus:
    desc: Run nexus in development mode
    dir: "./cmd/nexus/"
    env:
      KV2_DEVEL: "true"
    cmd: "go run ."
  lint:
    desc: Lint all files
    cmds:
      - "buf lint"
      - "golangci-lint run"
