// Copyright (c) Kyle Huggins
// SPDX-License-Identifier: BSD-3-Clause

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: nexus/v2/api.proto

// Package nexus provides APIs for managing encrypted secrets and their
// metadata. Nexus stores provided values as-is, and the client should
// encrypt the content prior to making the request.
package nexusv2connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v2 "github.com/hugginsio/kv2/api/nexus/v2"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// Kv2NexusServiceName is the fully-qualified name of the Kv2NexusService service.
	Kv2NexusServiceName = "nexus.v2.Kv2NexusService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// Kv2NexusServiceCreateSecretProcedure is the fully-qualified name of the Kv2NexusService's
	// CreateSecret RPC.
	Kv2NexusServiceCreateSecretProcedure = "/nexus.v2.Kv2NexusService/CreateSecret"
	// Kv2NexusServiceUpdateSecretProcedure is the fully-qualified name of the Kv2NexusService's
	// UpdateSecret RPC.
	Kv2NexusServiceUpdateSecretProcedure = "/nexus.v2.Kv2NexusService/UpdateSecret"
)

// Kv2NexusServiceClient is a client for the nexus.v2.Kv2NexusService service.
type Kv2NexusServiceClient interface {
	CreateSecret(context.Context, *connect.Request[v2.CreateSecretRequest]) (*connect.Response[v2.CreateSecretResponse], error)
	UpdateSecret(context.Context, *connect.Request[v2.UpdateSecretRequest]) (*connect.Response[v2.UpdateSecretResponse], error)
}

// NewKv2NexusServiceClient constructs a client for the nexus.v2.Kv2NexusService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewKv2NexusServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) Kv2NexusServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	kv2NexusServiceMethods := v2.File_nexus_v2_api_proto.Services().ByName("Kv2NexusService").Methods()
	return &kv2NexusServiceClient{
		createSecret: connect.NewClient[v2.CreateSecretRequest, v2.CreateSecretResponse](
			httpClient,
			baseURL+Kv2NexusServiceCreateSecretProcedure,
			connect.WithSchema(kv2NexusServiceMethods.ByName("CreateSecret")),
			connect.WithClientOptions(opts...),
		),
		updateSecret: connect.NewClient[v2.UpdateSecretRequest, v2.UpdateSecretResponse](
			httpClient,
			baseURL+Kv2NexusServiceUpdateSecretProcedure,
			connect.WithSchema(kv2NexusServiceMethods.ByName("UpdateSecret")),
			connect.WithClientOptions(opts...),
		),
	}
}

// kv2NexusServiceClient implements Kv2NexusServiceClient.
type kv2NexusServiceClient struct {
	createSecret *connect.Client[v2.CreateSecretRequest, v2.CreateSecretResponse]
	updateSecret *connect.Client[v2.UpdateSecretRequest, v2.UpdateSecretResponse]
}

// CreateSecret calls nexus.v2.Kv2NexusService.CreateSecret.
func (c *kv2NexusServiceClient) CreateSecret(ctx context.Context, req *connect.Request[v2.CreateSecretRequest]) (*connect.Response[v2.CreateSecretResponse], error) {
	return c.createSecret.CallUnary(ctx, req)
}

// UpdateSecret calls nexus.v2.Kv2NexusService.UpdateSecret.
func (c *kv2NexusServiceClient) UpdateSecret(ctx context.Context, req *connect.Request[v2.UpdateSecretRequest]) (*connect.Response[v2.UpdateSecretResponse], error) {
	return c.updateSecret.CallUnary(ctx, req)
}

// Kv2NexusServiceHandler is an implementation of the nexus.v2.Kv2NexusService service.
type Kv2NexusServiceHandler interface {
	CreateSecret(context.Context, *connect.Request[v2.CreateSecretRequest]) (*connect.Response[v2.CreateSecretResponse], error)
	UpdateSecret(context.Context, *connect.Request[v2.UpdateSecretRequest]) (*connect.Response[v2.UpdateSecretResponse], error)
}

// NewKv2NexusServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewKv2NexusServiceHandler(svc Kv2NexusServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	kv2NexusServiceMethods := v2.File_nexus_v2_api_proto.Services().ByName("Kv2NexusService").Methods()
	kv2NexusServiceCreateSecretHandler := connect.NewUnaryHandler(
		Kv2NexusServiceCreateSecretProcedure,
		svc.CreateSecret,
		connect.WithSchema(kv2NexusServiceMethods.ByName("CreateSecret")),
		connect.WithHandlerOptions(opts...),
	)
	kv2NexusServiceUpdateSecretHandler := connect.NewUnaryHandler(
		Kv2NexusServiceUpdateSecretProcedure,
		svc.UpdateSecret,
		connect.WithSchema(kv2NexusServiceMethods.ByName("UpdateSecret")),
		connect.WithHandlerOptions(opts...),
	)
	return "/nexus.v2.Kv2NexusService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case Kv2NexusServiceCreateSecretProcedure:
			kv2NexusServiceCreateSecretHandler.ServeHTTP(w, r)
		case Kv2NexusServiceUpdateSecretProcedure:
			kv2NexusServiceUpdateSecretHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedKv2NexusServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedKv2NexusServiceHandler struct{}

func (UnimplementedKv2NexusServiceHandler) CreateSecret(context.Context, *connect.Request[v2.CreateSecretRequest]) (*connect.Response[v2.CreateSecretResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("nexus.v2.Kv2NexusService.CreateSecret is not implemented"))
}

func (UnimplementedKv2NexusServiceHandler) UpdateSecret(context.Context, *connect.Request[v2.UpdateSecretRequest]) (*connect.Response[v2.UpdateSecretResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("nexus.v2.Kv2NexusService.UpdateSecret is not implemented"))
}
