# huggins.dev/kv2
# Default configuration for kv2's Nexus component.

persistence:
  enabled: true
  type: sqlite
  endpoint: "/data/kv2.db"
  backup:
    enabled: false
    schedule: ""
    endpoint: ""
  restore:
    enabled: false
  max-versions: 9

tailnet:
  enabled: true
  key-var: TS_AUTHKEY
  key-kms: ""
  hostname: kv2-nexus
  tls: false

kms:
  enabled: false
