// Copyright (c) Kyle Huggins
// SPDX-License-Identifier: BSD-3-Clause

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: relay/v2/api.proto

// Package relay provides APIs for retrieving secrets from a Nexus server.

package relayv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_relay_v2_api_proto protoreflect.FileDescriptor

const file_relay_v2_api_proto_rawDesc = "" +
	"\n" +
	"\x12relay/v2/api.proto\x12\brelay.v2B\x88\x01\n" +
	"\fcom.relay.v2B\bApiProtoP\x01Z-github.com/hugginsio/kv2/api/relay/v2;relayv2\xa2\x02\x03RXX\xaa\x02\bRelay.V2\xca\x02\bRelay\\V2\xe2\x02\x14Relay\\V2\\GPBMetadata\xea\x02\tRelay::V2b\x06proto3"

var file_relay_v2_api_proto_goTypes = []any{}
var file_relay_v2_api_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_relay_v2_api_proto_init() }
func file_relay_v2_api_proto_init() {
	if File_relay_v2_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_relay_v2_api_proto_rawDesc), len(file_relay_v2_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_relay_v2_api_proto_goTypes,
		DependencyIndexes: file_relay_v2_api_proto_depIdxs,
	}.Build()
	File_relay_v2_api_proto = out.File
	file_relay_v2_api_proto_goTypes = nil
	file_relay_v2_api_proto_depIdxs = nil
}
